# Generated by Django 4.1.7 on 2023-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_managers_account_commented_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_info',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание профиля'),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мужчина'), ('female', 'Женщина')], default='male', max_length=20, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер телефона'),
        ),
    ]
