# Generated by Django 4.1.7 on 2023-04-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_account_info_account_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='account',
            name='login',
            field=models.CharField(default='inst_login', max_length=150, unique=True, verbose_name='Логин'),
        ),
    ]
